### ISSUE TITLE
Use device IDs

### ISSUE THREAD

**Issue by alphapapa** [jgkamat/matrix-client-el#23]
We can set a device ID of our choosing, and cache it along with the access token (#22).  Note, though, that this might cause issues with using multiple Emacs processes with a Matrix account at the same time.  Normally that would probably be fine, but it might be annoying when developing and debugging.

We can also set a device ID description, something like `matrix-client.el @ hostname` seems like a good idea.  Hostnames aren't generally considered private on the Internet, e.g. they tend to show up in email headers even for hosts behind NAT.

**Comment by jgkamat** [comment]
Hostnames are definetly fine, on riot android at least, the device name shows up by default as well, so I think this is reasonable.

**Comment by alphapapa** [comment]
We do this now.
