### ISSUE TITLE
client-ng: Error with multibyte messages

### ISSUE THREAD

**Issue by alphapapa** [jgkamat/matrix-client-el#50]
I fixed this problem on `master`, which uses request.el, but now it's happening with `client-ng`, which now uses url.el.  I don't understand why it's happening.

Trying to send this message triggers it (the special quotation marks are not ASCII):
```
"""Three logicians walk into a bar.
The bartender asks “So, are you all having drinks?”
The first logician says “I don’t know.”
The second says “I don’t know.”
The third says “Yes!”"""
```
We encode messages in `matrix-send-message`:
```el
(a-list 'msgtype msgtype
        'body (encode-coding-string message 'utf-8))
```
But for some reason, this code in `url-http-create-request` (using Emacs 26.1) triggers the error:
```el
;; Bug#23750
    (unless (= (string-bytes request)
               (length request))
      (error "Multibyte text in HTTP request: %s" request))
```
Reading https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23750 doesn't help much, as it seems to be about the error message rather than the underlying problem.  And again, I don't understand why this is happening, because we encode it to `utf-8`, which should solve the problem.  For example:
```el
(setq argh "Three logicians walk into a bar.
      The bartender asks “So, are you all having drinks?”
      The first logician says “I don’t know.”
      The second says “I don’t know.”
      The third says “Yes!”")
(multibyte-string-p argh)  ;; => t
(multibyte-string-p (encode-coding-string argh 'utf-8))  ;; => nil
```
Of course, url.el is testing the length of the string with `string-bytes`, and Eli Zaretskii explains why in the bug report, but I need to re-read the messages to understand it all.  However, since we are not giving `url-http-create-request` a multibyte string, it seems like the error should not be raised, so maybe this is a new bug in url.el.  For example:
```el
(equal (string-bytes (encode-coding-string argh 'utf-8))
       (length (encode-coding-string argh 'utf-8)))  ;; => t
```

@jgkamat If you have any interest and insight into this, I'd appreciate it.  :)

**Comment by jgkamat** [comment]
Since you found a way to fix this, I don't think it's worth spending time figuring out why this is happening. My best guess is something goes wrong in the json decoding which results in multibyte text in the output of that step, though.

**Comment by alphapapa** [comment]
Wait, what? I thought you *really enjoyed debugging.*  :P

**Comment by jgkamat** [comment]
I *do*, but my computers are currently on fire so I already have *so much debugging to do* :rofl:
