### ISSUE TITLE
void function esxml-query-all

### ISSUE THREAD

**Issue by stardiviner** [jgkamat/matrix-client-el#63]
After I started with `matrix-client-ng-connect`. I got error:
```
error in process filter: matrix-client-ng--shr-mx-reply: Symbol’s function definition is void: esxml-query-all
error in process filter: Symbol’s function definition is void: esxml-query-all
uncompressing publicsuffix.txt.gz...done
Quit
user-error: Couldn’t identify where matrix-client is defined
rg finished (2 matches found)
user-error: Couldn’t find definition for function esxml-query-all
```

It might should be `xml-query-all`. I search on my Emacs, this is the function name.

And because I don't know which branch is currently active, so I don't know which branch to use and add PR. So I post issue here.

**Comment by alphapapa** [comment]
Please switch to the `master` branch and report whether it still happens.

**Comment by stardiviner** [comment]
In the `master` branch, the issue gone. Thanks.
