### ISSUE TITLE
Error (use-package): matrix-client/:catch: Unknown rx pattern: (rx bos "http" (optional "s") "://")

### ISSUE THREAD

**Issue by hexmode** [jgkamat/matrix-client-el#68]
When using [matrix-client-standalone.el](https://github.com/jgkamat/matrix-client-el/blob/master/misc/matrix-client-standalone.el), I get:
```
Error (use-package): matrix-client/:catch: Unknown rx pattern: (rx bos "http" (optional "s") "://")
```
in my `*Warnings*` buffer.

**Comment by jgkamat** [comment]
I think this is fixed by using Emacs 26. Are you using Emacs 25? I'm not sure
why that pattern wouldn't work in 25 though, it seems valid to me.

Mark A. Hershberger writes:

> When using [matrix-client-standalone.el](https://github.com/jgkamat/matrix-client-el/blob/master/misc/matrix-client-standalone.el), I get:
> ```
> Error (use-package): matrix-client/:catch: Unknown rx pattern: (rx bos "http" (optional "s") "://")
> ```
> in my `*Warnings*` buffer.

**Comment by hexmode** [comment]
No, I was using emacs25.  I have emacs compiled from git's master branch that produces a different problem, so I'll assume emacs26 solves this problem.

**Comment by alphapapa** [comment]
The `rx` `pcase` matcher was added in Emacs 26.  I've added a note to the readme about requiring Emacs 26+.
